"""UI Report Exporter module for ReportLab court-admissible PDF generation."""

from pathlib import Path
from typing import Dict, List, Any
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    HRFlowable,
)


def export_case_brief_pdf(
    case_id: str = "CASE-104",
    risk_report: Dict[str, Any] = None,
    audit_entries: List[Dict[str, Any]] = None,
    output_filepath: str = "outputs/case_brief_104.pdf",
) -> str:
    """Generates a court-admissible 1-page PDF Case Brief using ReportLab.

    Args:
        case_id: Case registration ID string.
        risk_report: Risk report dictionary generated by RuleEngine.
        audit_entries: List of audit log entries from Hasher.
        output_filepath: Target PDF file path.

    Returns:
        Absolute filepath string of the generated PDF document.
    """
    if not risk_report:
        risk_report = {
            "total_risk_score": 100,
            "threshold_label": "CRITICAL",
            "triggered_rules": [
                {
                    "rule_id": "R-001",
                    "title": "SIM Swap Prior to Fraud Transaction",
                    "score": 35,
                    "statutory_ref": "IT Act §66C",
                    "evidence": "SIM Swap on MSISDN +919845012345 at 14:11:00 (22 min before fraud).",
                },
                {
                    "rule_id": "R-002",
                    "title": "High-Velocity Multi-Hop Fund Laundering",
                    "score": 40,
                    "statutory_ref": "PMLA §3",
                    "evidence": "INR 95,000 transferred across 3 hops in 5m 42s.",
                },
                {
                    "rule_id": "R-004",
                    "title": "Sideloaded APK with Dangerous Permissions",
                    "score": 30,
                    "statutory_ref": "IT Act §43",
                    "evidence": "Fake banking APK installed with READ_SMS permissions.",
                },
            ],
        }

    if not audit_entries:
        audit_entries = [
            {
                "sequence": 1,
                "filename": "cdr_records.csv",
                "sha256": "0cab99950fdbc6b02b425bf7a1c8662fdb48c7f8ec2a49550274230dac3f1665",
                "size_bytes": 7833,
                "timestamp_utc": "2026-09-14T12:07:27Z",
            },
            {
                "sequence": 2,
                "filename": "bank_statement.csv",
                "sha256": "7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b",
                "size_bytes": 4512,
                "timestamp_utc": "2026-09-14T12:08:10Z",
            },
        ]

    out_path = Path(output_filepath)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    doc = SimpleDocTemplate(
        str(out_path),
        pagesize=letter,
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=36,
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "DocTitle",
        parent=styles["Heading1"],
        fontName="Helvetica-Bold",
        fontSize=18,
        leading=22,
        textColor=colors.HexColor("#1e293b"),
    )

    subtitle_style = ParagraphStyle(
        "DocSubTitle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10,
        leading=14,
        textColor=colors.HexColor("#64748b"),
    )

    heading_style = ParagraphStyle(
        "SectionHeading",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=12,
        leading=16,
        textColor=colors.HexColor("#0f172a"),
        spaceBefore=8,
        spaceAfter=4,
    )

    body_style = ParagraphStyle(
        "BodyTextCustom",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9,
        leading=12,
        textColor=colors.HexColor("#334155"),
    )

    elements = []

    # Title & Header
    elements.append(Paragraph("CYBER FRAUD FORENSIC CASE BRIEF", title_style))
    elements.append(Paragraph(f"Case Registration ID: #{case_id} | Admissible Evidence Brief", subtitle_style))
    elements.append(Spacer(1, 8))
    elements.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor("#0284c7"), spaceAfter=10))

    # Risk Score Banner Table
    score = risk_report.get("total_risk_score", 100)
    thresh = risk_report.get("threshold_label", "CRITICAL")
    score_data = [
        [
            Paragraph(f"<b>FORENSIC RISK SCORE:</b> {score} / 100", body_style),
            Paragraph(f"<b>THRESHOLD:</b> <font color='red'><b>{thresh}</b></font>", body_style),
            Paragraph("<b>EVIDENCE STATUS:</b> VERIFIED SHA-256", body_style),
        ]
    ]
    score_table = Table(score_data, colWidths=[200, 160, 180])
    score_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
            ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#cbd5e1")),
            ("PADDING", (0, 0), (-1, -1), 6),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ])
    )
    elements.append(score_table)
    elements.append(Spacer(1, 10))

    # Section 1: SHA-256 Preservation Table
    elements.append(Paragraph("1. Forensic SHA-256 Hash Preservation Log", heading_style))

    hash_table_data = [["Seq", "Artifact Filename", "SHA-256 Hex Digest (Chain)", "Size Bytes", "UTC Ingest Time"]]
    for entry in audit_entries[:4]:
        sha_short = entry.get("sha256", "")
        if len(sha_short) > 24:
            sha_short = f"{sha_short[:12]}...{sha_short[-12:]}"
        hash_table_data.append([
            str(entry.get("sequence", 1)),
            entry.get("filename", ""),
            sha_short,
            f"{entry.get('size_bytes', 0):,} B",
            entry.get("timestamp_utc", ""),
        ])

    hash_table = Table(hash_table_data, colWidths=[30, 110, 240, 70, 90])
    hash_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f172a")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("PADDING", (0, 0), (-1, -1), 4),
        ])
    )
    elements.append(hash_table)
    elements.append(Spacer(1, 10))

    # Section 2: Statutory Triggers Breakdown
    elements.append(Paragraph("2. Statutory Forensic Triggers & Evidence Breakdown", heading_style))

    rule_table_data = [["Rule", "Statutory Reference", "Trigger Description & Factual Evidence", "Weight"]]
    for rule in risk_report.get("triggered_rules", [])[:5]:
        rule_table_data.append([
            rule.get("rule_id", ""),
            rule.get("statutory_ref", ""),
            Paragraph(rule.get("evidence", ""), body_style),
            f"+{rule.get('score', 0)}",
        ])

    rule_table = Table(rule_table_data, colWidths=[50, 110, 330, 50])
    rule_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e293b")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("PADDING", (0, 0), (-1, -1), 4),
        ])
    )
    elements.append(rule_table)
    elements.append(Spacer(1, 10))

    # Section 3: Money Flow Topology Summary
    elements.append(Paragraph("3. Money Flow & Velocity Topology", heading_style))
    flow_text = (
        "<b>Path Traced:</b> Victim (AXIS-SURESH-9201) -&gt; Mule 1 (HDFC-MULE1-3847) -&gt; Mule 2 (SBI-MULE2-7731) -&gt; Koramangala ATM Cashout.<br/>"
        "<b>Total Amount:</b> INR 95,000.00 | <b>Velocity:</b> INR 16,101.69 / minute | <b>Hops:</b> 3 Steps in 5 mins 42 secs."
    )
    elements.append(Paragraph(flow_text, body_style))
    elements.append(Spacer(1, 15))

    # Footer Notice
    footer_text = (
        "Generated by AI-Powered Unified Cyber Fraud Correlator (Void Hacks 8.0). "
        "Court Admissible under Indian Evidence Act §65B / BSA 2023 §63."
    )
    elements.append(Paragraph(f"<font color='#64748b' size=7>{footer_text}</font>", body_style))

    doc.build(elements)
    return str(out_path.resolve())
