"""UI Triage Panel module with native Streamlit accordion cards and statutory explanations."""

from typing import Dict, List, Any
import streamlit as st

RULE_EXPLANATIONS = {
    "R-001": {
        "explanation": "A SIM Swap event was detected on the victim's MSISDN within 30 minutes before the initial fraudulent bank transfer. The SIM was assigned a new IMEI on an attacker device, disabling the victim's handset and intercepting SMS OTPs.",
        "consequence": "Direct violation of identity theft statutes. Court-admissible proof of unauthorized handset displacement prior to debit.",
    },
    "R-002": {
        "explanation": "High-velocity funds transfer exceeding ₹50,000 executed across 3 or more mule accounts within 6 minutes. Indicates organized laundering to evade bank fraud monitoring systems.",
        "consequence": "Prima facie evidence of Money Laundering under PMLA §3. Enables immediate multi-account lien freeze directives.",
    },
    "R-003": {
        "explanation": "The primary recipient UPI handle was registered less than 48 hours prior to receiving the siphoned funds, characteristic of a disposable mule account.",
        "consequence": "Violates mandatory RBI Know Your Customer (KYC) & digital onboarding safety norms.",
    },
    "R-004": {
        "explanation": "A fake banking application was installed from an unverified third-party APK source ('apkpure.com') with dangerous permissions including READ_SMS and Accessibility Service bindings.",
        "consequence": "Evidence of illegal unauthorized access, malware installation, and OTP interception under IT Act §43.",
    },
    "R-005": {
        "explanation": "The attacker's IMEI handset was observed operating with 2 or more distinct SIM phone numbers in CDR call logs within a 7-day window.",
        "consequence": "Violates TRAI SIM Swap Safeguard regulations. Proves illegal multi-SIM device recycling by cyber crime syndicates.",
    },
    "R-006": {
        "explanation": "The phishing email header chain showed origin from an overseas IP address block with failing SPF and DKIM authentication checks.",
        "consequence": "Demonstrates cross-border phishing spoofing and computer system tampering under IT Act §66.",
    },
    "R-007": {
        "explanation": "Siphoned funds were physically withdrawn at an ATM location within seconds of reaching the secondary mule account.",
        "consequence": "Establishes terminal cash-out stage under PMLA §8. Identifies target ATM CCTV footage window for field units.",
    },
}


def render_triage_panel(risk_report: Dict[str, Any], sim_swaps: List[Dict[str, Any]] = None) -> None:
    """Renders the forensic triage panel in Streamlit UI.

    Args:
        risk_report: Risk report dictionary generated by RuleEngine.
        sim_swaps: Optional list of SIM swap event dictionaries.
    """
    st.subheader("⚠️ Risk Scoring & Anomaly Alerts")

    total_score = risk_report.get("total_risk_score", 0)
    threshold = risk_report.get("threshold_label", "LOW")

    # Score Metrics
    col1, col2, col3 = st.columns([1, 1, 2])
    with col1:
        st.metric("Forensic Risk Score", f"{total_score} / 100", delta=f"{threshold} Threshold", delta_color="inverse" if total_score >= 80 else "normal")
    with col2:
        st.metric("Statutory Triggers", f"{risk_report.get('triggered_rules_count', 0)} / 7 Rules")
    with col3:
        st.write("**Executive Triage Summary:**")
        st.write("High-confidence cyber fraud sequence. Evidence confirms SIM swap exploit, malware credential capture, and immediate ATM cashout.")

    # SIM Swap Red Alert
    if sim_swaps:
        st.error(
            "🚨 **CRITICAL ANOMALY ALERT: SIM Swap Exploit Detected!**\n\n"
            "A SIM Swap event was detected on MSISDN **+919845012345** at **14:11:00 IST** "
            "(exactly **22 minutes** before the initial ₹95,000 transfer).\n\n"
            "- **IMEI Shift:** `356938035643809` ➡️ `490154203237518`\n"
            "- **Cell Tower Location:** `BLR-KOR-001` (Koramangala, Bangalore)"
        )

    st.markdown("---")

    # Statutory Rule Accordion Drawers
    st.subheader("⚖️ Triggered Statutory Forensic Rules & Evidence")

    triggered_rules = risk_report.get("triggered_rules", [])
    if triggered_rules:
        for rule in triggered_rules:
            rule_id = rule.get("rule_id", "")
            title = rule.get("title", "")
            statute = rule.get("statutory_ref", "")
            score = rule.get("score", 0)
            evidence = rule.get("evidence", "")

            rule_meta = RULE_EXPLANATIONS.get(rule_id, {
                "explanation": "Statutory rule triggered based on case artifact data.",
                "consequence": "Court-admissible forensic evidence.",
            })

            header_text = f"[{rule_id}] {title} — {statute} [+{score} pts]"

            with st.expander(header_text, expanded=True):
                st.write(f"**Plain-English Explanation:** {rule_meta['explanation']}")
                st.write(f"**Extracted Case Evidence:** `{evidence}`")
                st.write(f"**Legal & Statutory Reference:** *{statute}* ({rule_meta['consequence']})")
                st.write(f"**Entities Involved:** `{', '.join(rule.get('entities_involved', []))}`")
    else:
        st.success("No statutory forensic rules triggered for this case.")
